title: Jouster Documentation
description: Documentation for Jouster - A tool to track and manage test failures
baseurl: "/jouster"
url: "https://tsavo.github.io"

# Build settings
markdown: kramdown

# Default layout
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
